### ISSUE TITLE
@requestParam 어노테이션 적용하기

### ISSUE THREAD

**Issue by FourwingsY** [NHNNEXT/2015-01-HUDIWEB-CANDRUN#35]
스프링 어노테이션으로 `String email = request.getParameter("email"); `를 대체할 수 있습니다.
https://github.com/FourwingsY/2014-01-HUDI-WILDGOOSE/blob/dev/wildgoose/src/main/java/next/wildgoose/backcontroller/SessionController.java
를 참고하세요 :)

**Comment by JB1021** [comment]
파라미터를 스프링 어노테이션으로 받으면 어떤 점에서 좋죠??

**Comment by FourwingsY** [comment]
눈에 띄는 큰 장점은 없을 수도 있지만, 찾아보자면
컨트롤러가 직접 통신(req, res)에 관여하지 않고 로직에만 집중할 수 있다는 점...을 들 수 있겠습니다.
